f=imread('Lighthouse.jpg');
f=rgb2gray(f);
figure(1);imshow(f);title('origin');
g=imnoise(f,'salt & pepper',0.2);
figure(2);imshow(g);title('salt&pepper');
g1=double(g)/255;
j1=medfilt2(g1,'symmetric');
figure(3);imshow(j1);title('中值滤波');
j2=ordfilt2(g1,median(1:3*3),ones(3,3),'symmetric');
figure(4);imshow(j2);title('中点滤波');
j3=ordfilt2(g1,1,ones(3,3));
figure(5);imshow(j3);title('最小值滤波图像');
j4=ordfilt2(g1,9,ones(3,3));
figure(6);imshow(j4);title('最大滤波');